version: "3"

services:
  # NGINX
  nginx:
    image: graphmarket/nginx_cube:latest
    restart: unless-stopped
    hostname: nginx
    build:
      context: .
      dockerfile: ./compose/nginx_cube/Dockerfile
    ports:
      - "80:80"
      - "8282:8282"
    volumes:
      - /var/graph_market:/media
    links:
      - web_cube:web_cube
      - geo:geo
      - geo_flower:geo_flower
      - web_flower_cube:web_flower_cube
    depends_on:
      - web_cube
      - geo
  # WEB
  web_cube:
    image: graphmarket/web_cube:latest
    restart: unless-stopped
    hostname: web_cube
    build:
      context: .
      dockerfile: ./compose/web_cube/Dockerfile
    env_file:
      - env/web_cube
    volumes:
      - /var/graph_market:/var/graph_market
    links:
      - rabbit:rabbit
      - redis:redis
      - elasticsearch:elasticsearch
    extra_hosts:
      - "postgres:188.246.233.239"
    depends_on:
      - rabbit
      - redis
      - elasticsearch
    network_mode: "host"

  # WEB_CELERY
  web_celery_cube:
    image: graphmarket/web_celery_cube:latest
    restart: unless-stopped
    hostname: web_celery_cube
    build:
      context: .
      dockerfile: ./compose/web_celery_cube/Dockerfile
    env_file:
      - env/web_cube
    volumes:
      - /var/graph_market:/var/graph_market
    links:
      - rabbit:rabbit
      - redis:redis
    extra_hosts:
      - "postgres:188.246.233.239"
    depends_on:
      - rabbit
      - redis
      - elasticsearch
  # WEB_FLOWER
  web_flower_cube:
    image: graphmarket/web_flower_cube:latest
    restart: unless-stopped
    hostname: web_celery_cube
    build:
      context: .
      dockerfile: ./compose/web_flower_cube/Dockerfile
    env_file:
      - env/web_cube
    links:
      - rabbit
      - redis
    extra_hosts:
      - "postgres:188.246.233.239"
    depends_on:
      - web_celery_cube
      - rabbit
      - redis
  # ELASTICSEARCH
  elasticsearch:
    image: graphmarket/elasticsearch:latest
    restart: unless-stopped
    hostname: elasticsearch
    volumes:
      - /var/graph_market:/var/graph_market
  # GEO
  geo:
    image: graphmarket/geo_cube:latest
    restart: unless-stopped
    hostname: geo
    build:
      context: .
      dockerfile: ./compose/geo/Dockerfile
    env_file:
      - env/geo
    extra_hosts:
      - "postgres:188.246.233.239"
  # GEO_CELERY
  geo_celery:
    image: graphmarket/geo_celery_cube:latest
    restart: unless-stopped
    hostname: geo_celery
    build:
      context: .
      dockerfile: ./compose/geo/Dockerfile
    env_file:
      - env/geo
    volumes:
      - /var/graph_market:/var/graph_market
    links:
      - rabbit:rabbit
      - redis:redis
    extra_hosts:
      - "postgres:188.246.233.239"
    depends_on:
      - rabbit
      - redis
  # GEO_FLOWER
  geo_flower:
    image: graphmarket/geo_flower_cube:latest
    restart: unless-stopped
    hostname: geo_celery
    build:
      context: .
      dockerfile: ./compose/geo/Dockerfile
    env_file:
      - env/geo
    links:
      - rabbit
      - redis
    extra_hosts:
      - "postgres:188.246.233.239"
    depends_on:
      - geo_celery
      - rabbit
      - redis
  # RABBITMQ
  rabbit:
    image: rabbitmq:3.6.11-management
    restart: unless-stopped
    hostname: rabbit
    volumes:
      - "./env/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:rw"
      - "./env/rabbit_definitions.json:/etc/rabbitmq/definitions.json:rw"
  # REDIS
  redis:
    image: redis:latest
    restart: unless-stopped
    hostname: redis
