# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-08 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import yandex_money.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_paymentRelations'),
        ('yandex_money', '0001_yandexMoneyInitial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cart.Order2'),
        ),
        migrations.AddField(
            model_name='payment',
            name='uuid',
            field=models.CharField(default=yandex_money.models.get_default_as_uuid, max_length=64, verbose_name='уникальный идентификатор'),
        ),
    ]
