# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-28 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_money', '0003_paymentUiid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='shop_id',
            field=models.PositiveIntegerField(default='523666', verbose_name='ID магазина'),
        ),
    ]
