# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-12 13:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=256, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone_number', models.CharField(blank=True, max_length=12, verbose_name='Телефон')),
                ('client_notes', models.TextField(blank=True, max_length=2000, verbose_name='Пожелания')),
                ('address', models.TextField(blank=True, max_length=2000, verbose_name='Адрес доставки')),
                ('managet_notes', models.TextField(blank=True, max_length=2000, verbose_name='Служебные заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('state', models.CharField(choices=[('новый', 'Новый'), ('недозвон', 'Недозвон'), ('доставка', 'Доставка'), ('согласован', 'Согласован'), ('выполнен', 'Выполнен'), ('отменён', 'Отменён'), ('отменён: недозвон', 'Отменён: недозвон')], default='новый', max_length=100, verbose_name='Состояние заказа')),
                ('source', models.CharField(choices=[('cart', 'Корзина'), ('callback', 'Обратный звонок'), ('product-page', 'Страница товара')], default='cart', max_length=128, verbose_name='Источник заказа')),
                ('delivery_mode', models.CharField(blank=True, choices=[('', 'не выбрано'), ('SDEK_COURIER', 'курьером'), ('SDEK_POINT', 'постамат сдэк'), ('PICK_POINT', 'pickpoint'), ('POST_SERVICE', 'почта России')], default='', max_length=128, verbose_name='способ доставки')),
                ('delivery_code', models.CharField(blank=True, default='', max_length=128, verbose_name='код доставки')),
                ('delivery_mode_selected', models.BooleanField(default=False, verbose_name='способ доставки выбран')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'verbose_name': 'Заказ',
            },
        ),
        migrations.CreateModel(
            name='Order2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(blank=True, verbose_name='Последнее изменение')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('manager_notes', models.TextField(blank=True, max_length=2000, verbose_name='Служебные заметки')),
                ('state', models.CharField(choices=[('новый', 'Новый'), ('недозвон', 'Недозвон'), ('доставка', 'Доставка'), ('согласован', 'Согласован'), ('выполнен', 'Выполнен'), ('отменён', 'Отменён'), ('отменён: недозвон', 'Отменён: недозвон')], default='новый', max_length=100, verbose_name='Состояние заказа')),
                ('source', models.CharField(choices=[('cart', 'Корзина'), ('callback', 'Обратный звонок'), ('product-page', 'Страница товара')], default='cart', max_length=128, verbose_name='Источник заказа')),
                ('assist_key', models.CharField(blank=True, default=0, max_length=128, validators=[django.core.validators.RegexValidator(message='vendor_code valid error', regex='^\\d+$')])),
                ('assist_status', models.CharField(blank=True, choices=[('', ''), ('in_process', 'in_process'), ('approved', 'approved')], default='', max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Заказы2',
                'verbose_name': 'Заказ2',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('total_price', models.PositiveIntegerField(verbose_name='Полная цена')),
                ('full_url', models.CharField(max_length=512, verbose_name='URL')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('vendor_code', models.CharField(max_length=1024, verbose_name='Артикул')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Order')),
            ],
            options={
                'verbose_name_plural': 'Пункты Заказа',
                'verbose_name': 'Пункт Заказа',
            },
        ),
    ]
