# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-10 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_customerNotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order2',
            name='notified_by_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order2',
            name='notified_by_sms',
            field=models.BooleanField(default=False),
        ),
    ]
