# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-01 14:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartNotificationStatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order2',
            name='delivery_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'change_date': '', 'delivery_service': '', 'dispatch_number': '', 'history': [], 'service_status_code': None, 'state_description': '', 'status_code': None}),
        ),
    ]
