# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-17 13:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_order2_cpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order2',
            name='delivery_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'change_date': '', 'dispatch_number': '', 'history': [], 'service': '', 'service_status_code': None, 'state_description': '', 'status_code': None, 'sum': None}),
        ),
    ]
