# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-24 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20181117_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='order2',
            name='_order',
            field=models.IntegerField(default=10, verbose_name='порядок'),
        ),
        migrations.AlterField(
            model_name='order2',
            name='state',
            field=models.CharField(choices=[('новый', 'Новый'), ('недозвон', 'Недозвон'), ('недозвон 2', 'Недозвон 2'), ('доставка', 'Доставка'), ('согласован', 'Согласован'), ('выполнен', 'Выполнен'), ('отменён', 'Отменён'), ('отменён: недозвон', 'Отменён: недозвон'), ('вручен', 'вручен'), ('отказ', 'Отказ')], default='новый', max_length=100, verbose_name='Состояние заказа'),
        ),
    ]
