version: "3"

services:
  # NGINX
  nginx:
    image: graphmarket/nginx_cube:latest
    restart: unless-stopped
    hostname: nginx
    build:
      context: .
      dockerfile: ./compose/nginx_cube/Dockerfile
    ports:
      - "80:80"
      - "8282:8282"
    volumes:
      - /var/graph_market:/media
    links:
      - web_cube:web_cube
      - geo:geo
      - geo_flower:geo_flower
      - web_flower_cube:web_flower_cube
    depends_on:
      - web_cube
      - geo
  # WEB
  web_cube:
    image: graphmarket/web_cube:latest
    restart: unless-stopped
    hostname: web_cube
    build:
      context: .
      dockerfile: ./compose/web_cube/Dockerfile
    env_file:
      - env/web_cube
    volumes:
      - /var/graph_market:/var/graph_market
    links:
      - rabbit:rabbit
      - redis:redis
      - elasticsearch:elasticsearch
      - postgres_web:postgres
    depends_on:
      - rabbit
      - redis
      - elasticsearch
      - postgres_web
      - postgres_geo
  # WEB_CELERY
  web_celery_cube:
    image: graphmarket/web_celery_cube:latest
    restart: unless-stopped
    hostname: web_celery_cube
    build:
      context: .
      dockerfile: ./compose/web_celery_cube/Dockerfile
    env_file:
      - env/web_cube
    volumes:
      - /var/graph_market:/var/graph_market
    links:
      - rabbit:rabbit
      - redis:redis
      - postgres_web:postgres
    depends_on:
      - rabbit
      - redis
      - elasticsearch
      - postgres_web
      - postgres_geo
  # WEB_FLOWER
  web_flower_cube:
    image: graphmarket/web_flower_cube:latest
    restart: unless-stopped
    hostname: web_celery_cube
    build:
      context: .
      dockerfile: ./compose/web_flower_cube/Dockerfile
    env_file:
      - env/web_cube
    links:
      - rabbit
      - redis
      - postgres_web:postgres
    depends_on:
      - web_celery_cube
      - rabbit
      - redis
      - postgres_web
      - postgres_geo
  # ELASTICSEARCH
  elasticsearch:
    image: graphmarket/elasticsearch:latest
    restart: unless-stopped
    hostname: elasticsearch
    volumes:
      - /var/graph_market:/var/graph_market
  # GEO
  geo:
    image: graphmarket/geo:latest
    restart: unless-stopped
    hostname: geo
    env_file:
      - env/geo
    links:
      - postgres_geo:postgres
    depends_on:
      - postgres_web
      - postgres_geo
  # GEO_CELERY
  geo_celery:
    image: graphmarket/geo_celery:latest
    restart: unless-stopped
    hostname: geo_celery
    env_file:
      - env/geo
    volumes:
      - /var/graph_market:/var/graph_market
    links:
      - rabbit:rabbit
      - redis:redis
      - postgres_geo:postgres
    depends_on:
      - rabbit
      - redis
      - postgres_web
      - postgres_geo
  # GEO_FLOWER
  geo_flower:
    image: graphmarket/geo_flower:latest
    restart: unless-stopped
    hostname: geo_celery
    env_file:
      - env/geo
    links:
      - rabbit
      - redis
      - postgres_geo:postgres
    depends_on:
      - geo_celery
      - rabbit
      - redis
      - postgres_web
      - postgres_geo
  # RABBITMQ
  rabbit:
    image: rabbitmq:3.6.11-management
    restart: unless-stopped
    hostname: rabbit
    volumes:
      - "./env/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:rw"
      - "./env/rabbit_definitions.json:/etc/rabbitmq/definitions.json:rw"
  # REDIS
  redis:
    image: redis:latest
    restart: unless-stopped
    hostname: redis
  # REDIS

  # Postgres WEB
  postgres_web:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - /var/postgresql_web/data:/var/postgresql_web/data
    env_file:
      - env/postgres_web

  # Postgres GEO
  postgres_geo:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - /var/postgresql_geo/data:/var/postgresql_geo/data
    env_file:
      - env/postgres_geo



