# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-18 11:50
from __future__ import unicode_literals

import core.db.base.fields.displayable_url_field
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cubes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubescategorynode',
            name='slug',
            field=core.db.base.fields.displayable_url_field.DisplayableURLField(editable=False, max_length=2048, unique=True, validators=[django.core.validators.RegexValidator(message='slug valid error', regex='^(($)|(([-_\\da-z]+/)+$))')], verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='cubesproductcard',
            name='slug',
            field=core.db.base.fields.displayable_url_field.DisplayableURLField(editable=False, max_length=2048, unique=True, validators=[django.core.validators.RegexValidator(message='slug valid error', regex='^(($)|(([-_\\da-z]+/)+$))')], verbose_name='URL'),
        ),
    ]
