# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-01 15:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cubes', '0002_slugChanged'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cubesproductcard',
            managers=[
                ('public', django.db.models.manager.Manager()),
            ],
        ),
    ]
