# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-01 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cubes', '0004_auto_20180601_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubesproductcard',
            name='product_type',
            field=models.CharField(blank=True, choices=[('', 'Не задано'), ('CUBE', 'CUBE'), ('BAG', 'BAG'), ('SUITCASE', 'SUITCASE'), ('PURSE', 'PURSE')], default='', max_length=128, verbose_name='Тип продукта'),
        ),
    ]
