# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-27 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cubes', '0005_auto_20180601_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubesattribute',
            name='unit',
            field=models.CharField(blank=True, max_length=256, verbose_name='Единица измерения'),
        ),
    ]
