# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-16 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cubes', '0007_shortDescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CubesProductVideoReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(blank=True, verbose_name='Последнее изменение')),
                ('order', models.IntegerField(default=0, verbose_name='порядок')),
                ('youtube_code', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='код Youtube')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reviews', to='shop_cubes.CubesProductCard')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cubesproductvideoreview',
            unique_together=set([('product', 'youtube_code')]),
        ),
    ]
