# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-28 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cubes', '0009_productCardReview'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubesproductcardreview',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved by admin'),
        ),
    ]
