# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-30 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cubes', '0010_productCardReviewApprovedField'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cubesproductcardreview',
            name='approved',
        ),
        migrations.AddField(
            model_name='cubesproductcardreview',
            name='status',
            field=models.CharField(choices=[('новый', 'Новый'), ('одобрен', 'Одобрен'), ('отклонен', 'Отклонен')], default='новый', max_length=32, verbose_name='статус отзыва'),
        ),
    ]
