# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-03 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cubes', '0011_productCardReviewStatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubesproductcardreview',
            name='_author',
            field=models.CharField(blank=True, max_length=255, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='cubesproductcardreview',
            name='status',
            field=models.CharField(choices=[('новый', 'Новый'), ('одобрен', 'Одобрен'), ('отклонен', 'Отклонен')], db_index=True, default='новый', max_length=32, verbose_name='статус отзыва'),
        ),
    ]
