# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-06 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cubes', '0012_reviewAuthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubesproductcard',
            name='rating',
            field=models.PositiveIntegerField(choices=[(10, '10'), (9, '9'), (8, '8'), (7, '7'), (6, '6'), (5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1'), (0, '0')], db_index=True, default=0),
        ),
    ]
