# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-07 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cubes', '0015_productCardSelections'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubesproductcard',
            name='recently_bought',
            field=models.BooleanField(default=False, verbose_name='Куплен недавно'),
        ),
    ]
