# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-30 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cubes', '0016_recenltyBought'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubesproductcard',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='количество на складе'),
        ),
        migrations.AddField(
            model_name='cubesproductcard',
            name='stored',
            field=models.BooleanField(default=False, verbose_name='был закуплен'),
        ),
    ]
