# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-02 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cubes', '0017_OfferStore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubesattribute',
            name='is_default_filter',
            field=models.BooleanField(db_index=True, default=False, verbose_name='фильтр по умолчанию'),
        ),
    ]
