# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-02 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cubes', '0018_auto_20181202_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubescategorynode',
            name='order',
            field=models.IntegerField(default=0, verbose_name='порядок'),
        ),
    ]
