# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-04 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='имя')),
                ('surname', models.CharField(blank=True, max_length=256, verbose_name='фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=256, verbose_name='отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='нативный юзер')),
            ],
        ),
    ]
