# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-28 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profilePhoneNumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserComment',
        ),
    ]
