links_mapping = {
    'Кубы NxNxN': 'https://www.kubomarket.ru/catalog/kuby-nxnxn/',
    '2x2': 'https://www.kubomarket.ru/catalog/kuby-nxnxn/2x2/',
    '3x3': 'https://www.kubomarket.ru/catalog/kuby-nxnxn/3x3/',
    '4x4': 'https://www.kubomarket.ru/catalog/kuby-nxnxn/4x4/',
    '5x5': 'https://www.kubomarket.ru/catalog/kuby-nxnxn/5x5/',
    '6x6': 'https://www.kubomarket.ru/catalog/kuby-nxnxn/6x6/',
    '7x7': 'https://www.kubomarket.ru/catalog/kuby-nxnxn/7x7/',
    '8x8': 'https://www.kubomarket.ru/catalog/kuby-nxnxn/8x8/',
    '9x9': 'https://www.kubomarket.ru/catalog/kuby-nxnxn/9x9/',
    '10x10': 'https://www.kubomarket.ru/catalog/kuby-nxnxn/10x10/',
    '11x11': 'https://www.kubomarket.ru/catalog/kuby-nxnxn/11x11/',
    '13x13': 'https://www.kubomarket.ru/catalog/kuby-nxnxn/13x13/',
    'Профессиональный': 'https://www.kubomarket.ru/catalog/kuby-nxnxn/professionalnyj/',
    'Магнитный': 'https://www.kubomarket.ru/catalog/kuby-nxnxn/3x3/magnitnye/',
    "Calvin's Puzzle": 'https://www.kubomarket.ru/catalog/calvins-puzzle/',
    'Cast Puzzle': 'https://www.kubomarket.ru/catalog/cast-puzzle/',
    'CubeTwist': 'https://www.kubomarket.ru/catalog/cubetwist/',
    'Cyclone Boys': 'https://www.kubomarket.ru/catalog/cyclone-boys/',
    'Dayan': 'https://www.kubomarket.ru/catalog/dayan/',
    'DianSheng': 'https://www.kubomarket.ru/catalog/diansheng/',
    'FangCun': 'https://www.kubomarket.ru/catalog/fangcun/',
    'Fangshi': 'https://www.kubomarket.ru/catalog/fangshi/',
    'FanXin': 'https://www.kubomarket.ru/catalog/fanxin/',
    'GAN': 'https://www.kubomarket.ru/catalog/gan/',
    'KungFu': 'https://www.kubomarket.ru/catalog/kungfu/',
    'LanLan': 'https://www.kubomarket.ru/catalog/lanlan/',
    'LimCube': 'https://www.kubomarket.ru/catalog/limcube/',
    'Maru': 'https://www.kubomarket.ru/catalog/maru/',
    "Meffert's": 'https://www.kubomarket.ru/catalog/mefferts/',
    'MF8': 'https://www.kubomarket.ru/catalog/mf8/',
    'MoFangGe': 'https://www.kubomarket.ru/catalog/mofangge/',
    'MoYu': 'https://www.kubomarket.ru/catalog/moyu/',
    'QJ': 'https://www.kubomarket.ru/catalog/qj/',
    'Recent Toys': 'https://www.kubomarket.ru/catalog/recent-toys/',
    "Rubik's": 'https://www.kubomarket.ru/catalog/rubiks/',
    'ShengShou': 'https://www.kubomarket.ru/catalog/shengshou/',
    'Very Puzzle': 'https://www.kubomarket.ru/catalog/very-puzzle/',
    'WitEden': 'https://www.kubomarket.ru/catalog/witeden/',
    'Yuxin': 'https://www.kubomarket.ru/catalog/yuxin/',
    'Xiaomi': 'https://www.kubomarket.ru/catalog/xiaomi/',
    'Z-Cube': 'https://www.kubomarket.ru/catalog/z-cube/',
    'Нестандартные': 'https://www.kubomarket.ru/catalog/nestandartnoj-formy/',
    'Необычной формы': 'https://www.kubomarket.ru/catalog/nestandartnoj-formy/neobychnoj-formy/',
    'Зеркальные': 'https://www.kubomarket.ru/catalog/nestandartnoj-formy/zerkalnye/',
    'Кубоиды и Бандажи': 'https://www.kubomarket.ru/catalog/nestandartnoj-formy/kuboidy-i-bandazhi/',
    'Магия Рубика': 'https://www.kubomarket.ru/catalog/nestandartnoj-formy/magiya-rubika/',
    'Пирамидки': 'https://www.kubomarket.ru/catalog/nestandartnoj-formy/piramidki/',
    'Скваеры': 'https://www.kubomarket.ru/catalog/nestandartnoj-formy/skvaery/',
    'Скьюбы': 'https://www.kubomarket.ru/catalog/nestandartnoj-formy/skyuby/',
    'Мегаминксы': 'https://www.kubomarket.ru/catalog/nestandartnoj-formy/megaminksy/',
    'Змейки рубика': 'https://www.kubomarket.ru/catalog/nestandartnoj-formy/zmejki-rubika/',
    'Неокуб': 'https://www.kubomarket.ru/catalog/neokub/',
}
